IF  EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[HR_KONTRAK]') AND type in (N'U'))
BEGIN
		DROP TABLE [dbo].[HR_KONTRAK]
END
CREATE TABLE [dbo].[HR_KONTRAK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KODE] [varchar](20) NULL,
	[DESKRIPSI] [varchar](100) NULL,
	[DOKUMEN_PATH] [varchar](150) NULL,
	[DOKUMEN_NAME] [varchar](50) NULL,
	[KODE_UNIT_KERJA] [nvarchar] (5) NULL,
	[KODE_POSISI] [nvarchar] (5) NULL,
	[KODE_MST_JABATAN] [nvarchar] (10) NULL,
	[NIK] [varchar](10) NULL,
	[STATUS_PEGAWAI] [bit] NULL,
	[TANGGAL_MULAI_KONTRAK] [date] NULL,
	[TANGGAL_AKHIR_KONTRAK] [date] NULL,
	[IS_SHIFT] [varchar](1) NULL,
	[IS_CUTI] [varchar](1) NULL,
	[CRE_DATE] [datetime] NOT NULL,
	[CRE_BY] [nvarchar](15) NOT NULL,
	[CRE_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[MOD_DATE] [datetime] NOT NULL,
	[MOD_BY] [nvarchar](15) NOT NULL,
	[MOD_IP_ADDRESS] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_HR_KONTRAK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


