IF  EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[REFF_STATUS_PEGAWAI]') AND type in (N'U'))
BEGIN
		DROP TABLE [dbo].[REFF_STATUS_PEGAWAI]
END

CREATE TABLE [dbo].[REFF_STATUS_PEGAWAI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KODE] [nvarchar](5) NOT NULL,
	[DESKRIPSI] [nvarchar](100) NULL,
	[CRE_DATE] [datetime] NOT NULL,
	[CRE_BY] [nvarchar](15) NOT NULL,
	[CRE_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[MOD_DATE] [datetime] NOT NULL,
	[MOD_BY] [nvarchar](15) NOT NULL,
	[MOD_IP_ADDRESS] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_REFF_STATUS_PEGAWAI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
--SELECT * FROM REFF_STATUS_PEGAWAI
INSERT INTO REFF_STATUS_PEGAWAI
			(KODE,		DESKRIPSI,			CRE_DATE,		CRE_BY,			CRE_IP_ADDRESS,		MOD_DATE,		MOD_BY,			MOD_IP_ADDRESS)
SELECT		'T',		'Tetap',			GETDATE(),		'Anas',			'192.127.0.1',		GETDATE(),		'Anas',			'192.127.0.1' UNION
SELECT		'CT',		'Calon Tetap',		GETDATE(),		'Anas',			'192.127.0.1',		GETDATE(),		'Anas',			'192.127.0.1' UNION
SELECT		'HT',		'Harian Tetap',		GETDATE(),		'Anas',			'192.127.0.1',		GETDATE(),		'Anas',			'192.127.0.1' UNION
SELECT		'HNR',		'Honor',			GETDATE(),		'Anas',			'192.127.0.1',		GETDATE(),		'Anas',			'192.127.0.1'
