CREATE TABLE [dbo].[HR_PEGAWAI_PENDIDIKAN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NIK] [varchar](20) NULL,
	[KODE_JENJANG_PENDIDIKAN] [nvarchar] (5) NULL,
	[NAMA_SEKOLAH] [varchar](50) NULL,
	[JURUSAN] [varchar](50) NULL,
	[TAHUN_MULAI] [varchar](4) NULL,
	[TAHUN_LULUS] [varchar](4) NULL,
	[IJAZAH] [bit] NULL,
	[ATTACH_PATH] [varchar](100) NULL,
	[ATTACH_NAME] [varchar](50) NULL,
	[CRE_DATE] [datetime] NOT NULL,
	[CRE_BY] [nvarchar](15) NOT NULL,
	[CRE_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[MOD_DATE] [datetime] NOT NULL,
	[MOD_BY] [nvarchar](15) NOT NULL,
	[MOD_IP_ADDRESS] [nvarchar](15) NOT NULL,	
 CONSTRAINT [PK_HR_PEGAWAI_PENDIDIKAN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]