IF  EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[HR_ABSENSI_REKAP]') AND type in (N'U'))
BEGIN
		DROP TABLE [dbo].[HR_ABSENSI_REKAP]
END
CREATE TABLE [dbo].[HR_ABSENSI_REKAP](
	[ID] [int] IDENTITY(1,1) NOT NULL,	
	[NIK] [varchar](10) NULL,
	[NAMA] [varchar](10) NULL,
	[TANGGAL_AWAL] [date] NULL,	
	[TANGGAL_AKHIR] [date] NULL,	
	[TELAT] INTEGER NULL,
	[PULANGCEPAT] INTEGER NULL,
	[HADIR] INTEGER NULL,
	[SAKIT] INTEGER NULL,
	[CUTI] INTEGER NULL,
	[IJIN] INTEGER NULL,
	[ALPHA] INTEGER NULL,
	[CRE_DATE] [datetime] NOT NULL,
	[CRE_BY] [nvarchar](15) NOT NULL,
	[CRE_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[MOD_DATE] [datetime] NOT NULL,
	[MOD_BY] [nvarchar](15) NOT NULL,
	[MOD_IP_ADDRESS] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_HR_ABSENSI_REKAP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


