USE [HRMSPCM]
GO
/****** Object:  StoredProcedure [dbo].[SP_MST_TUNJANGAN_JABATAN_GETROW]    Script Date: 08/08/2017 22:27:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[SP_MST_TUNJANGAN_JABATAN_GETROW]
	(
	  @p_ID		int
	) 
	as
	begin
		select	a.ID,
				a.KODE,	
				a.KODE_JENIS_TUNJANGAN,
			    a.KODE_MASTER_JABATAN,			
				b.DESKRIPSI AS DESKRIPSI_TUNJANGAN,
				D.DESKRIPSI AS DESKRIPSI_JABATAN,
                a.NOMINAL,
                a.STATUS               			
		from	MST_TUNJANGAN_JABATAN a
		INNER JOIN REFF_JENIS_TUNJANGAN b on a.KODE_JENIS_TUNJANGAN = b.KODE
		INNER JOIN MST_JABATAN C ON A.KODE_MASTER_JABATAN = C.KODE	
		INNER JOIN REFF_JENIS_JABATAN D ON D.KODE = C.KODE_JABATAN	
		where	a.ID	= @p_ID
	end